---
title: "data_augment"
format: html
editor: visual
---

# Augmenting data

```{r}
library("tidyverse")

source("../R/99_proj_func.R")
```

```{r}
dir.create("../data/augmented_data", recursive = TRUE, showWarnings = FALSE)
```

## Table 2 - Maria

```{r}
clean_2 <- read_tsv(file = "../data/clean_data/clean_2.tsv", show_col_types = FALSE)

#Computing medians and log fold change of the gene expression among different cell types

panel_df <- clean_2 |>
  rowwise() |>
  mutate(
    logLFQ_median = median(c_across(starts_with("logLFQ_")), na.rm = TRUE),
    logFC_astro   = logLFQ_astro  - logLFQ_median,
    logFC_micro   = logLFQ_micro  - logLFQ_median,
    logFC_neuron  = logLFQ_neuron - logLFQ_median,
    logFC_oligo   = logLFQ_oligo  - logLFQ_median
  ) |>
  ungroup()

#Constructing the table:

astro_df <- panel_df |> 
  select(gene, logLFQ = logLFQ_astro, logFC = logFC_astro) |>
  mutate(type = "Astrocytes")

micro_df <- panel_df |> 
  select(gene, logLFQ = logLFQ_micro, logFC = logFC_micro) |>
  mutate(type = "Microglia")

neuron_df <- panel_df |> 
  select(gene, logLFQ = logLFQ_neuron, logFC = logFC_neuron) |>
  mutate(type = "Neurons")

oligo_df <- panel_df |> 
  select(gene, logLFQ = logLFQ_oligo, logFC = logFC_oligo) |>
  mutate(type = "Oligodendrocytes")

all_df <- bind_rows(
  astro_df, micro_df, neuron_df, oligo_df
)

#Adding the markers of each cell type
astro_markers       <- c("Aqp4", "Gfap", "Glast", "Aldh1l1")
micro_markers       <- c("Iba1", "Tlr2", "Tlr7", "CD86")
neuron_markers      <- c("Snap25", "Tubb3", "Calb1", "Syt1")
oligo_markers       <- c("Cnp1", "Sox10", "Mbp", "Mag", "Mog", "Plp1")

all_df <- all_df |>
  mutate(
    category = case_when(
      gene %in% astro_markers  ~ "Astrocyte markers",
      gene %in% micro_markers  ~ "Microglia markers",
      gene %in% neuron_markers ~ "Neuron markers",
      gene %in% oligo_markers  ~ "Oligodendrocyte markers",
      TRUE                     ~ "Other"
    )
  ) |>
  filter(is.finite(logFC), is.finite(logLFQ))

# Writing the table to augmented data folder data/data_augmented in tsv format

write_tsv(all_df, "../data/augmented_data/table_2_log.tsv")

```

## Table 3 - Louise

## Table 3+5 - Renata

### Table 3

```{r}
clean_3 <- read_tsv(file = "../data/clean_data/clean_3.tsv", show_col_types = FALSE)
#View(clean_3)

```

```{r}
rna_prefixes <- c(
  rna_oligo_div1   = "rpkm_oligodendrocytes_div1_",
  rna_oligo_div2_5 = "rpkm_oligodendrocytes_div2_5_",
  rna_oligo_div4   = "rpkm_oligodendrocytes_div4_",
  rna_microglia    = "rpkm_adult_microglia_",
  rna_astro        = "rpkm_astrocytes_",
  rna_neuron_div5  = "rpkm_cortical_neurons_div05_",
  rna_neuron_div10 = "rpkm_cortical_neurons_div10_"
)
```

```{r}
aug_3 <- clean_3 |>
  mutate(across(starts_with("rpkm_"), log2p1)) |>  # log2(x+1) on all rpkm columns
  mean_across_col(rna_prefixes) #|>                 # calculate means per cell type
  # select(rna_oligo_div1:rna_neuron_div10, gene_name)

#aug_3 
```

```{r}
# writing a table to augmented data folder data/data_augmented in tsv format

write_tsv(aug_3, "../data/augmented_data/table_3_log_means.tsv")
```

### Table 5

```{r}
clean_5 <- read_tsv(file = "../data/clean_data/clean_5.tsv", show_col_types = FALSE)
clean_5_separate_gene_names <- read_tsv(file = "../data/clean_data/clean_5_separate_gene_names.tsv", show_col_types = FALSE)
```

```{r}
prot_prefixes <- c(
  prot_microglia    = "adult_microglia_",
  prot_astro        = "astrocytes_",
  prot_neuron_div5  = "neurons_div05_",
  prot_neuron_div10 = "neurons_div10_",
  prot_oligo_div1   = "oligodendrocytes_div1_",
  prot_oligo_div2_5 = "oligodendrocytes_div2_5_",
  prot_oligo_div4   = "oligodendrocytes_div4_"
)
```

```{r}
aug_5 <- clean_5 |> 
  mutate(across(adult_microglia_1:oligodendrocytes_div4_3, log2p1)) |> # applying log2
  mean_across_col(prot_prefixes) |> #df is provided by pipe
  mutate(gene_name = gene_names) #|> #renaming the column for future merging with rna df
  # select(gene_name, protein_names, prot_microglia:prot_oligo_div4) #saving only new cols and names 
  
aug_5
```

```{r}
# writing a table to augmented data folder data/data_augmented in tsv format

write_tsv(aug_5, "../data/augmented_data/table_5_log_means.tsv")
```
