---
title: "Figure2a"
format: html
editor: visual
---

Libraries

```{r}
#| echo: false
library(tidyverse)
library(ggplot2)
library(hrbrthemes)
```

Data reading

```{r}
#| echo: false
clean_3 <- read_tsv(file = "../data/clean_data/clean_3.tsv", show_col_types = FALSE)
clean_5 <- read_tsv(file = "../data/clean_data/clean_5.tsv", show_col_types = FALSE)
```

Proteomics data

```{r}
clean_5 <- clean_5 |> 
  select(c(3:26)) |>
  mutate(across(everything(), as.numeric))
```

```{r}
corr_mat_p <- cor(clean_5, use = "pairwise.complete.obs", method = "pearson")

corr_long_p <- corr_mat_p |>
  as.data.frame() |>
  rownames_to_column("rep1") |>
  pivot_longer(
    cols = -rep1,
    names_to = "rep2",
    values_to = "correlation"
  )

corr_long_p <- corr_long_p |>
  mutate(
    rep1 = case_when(
      grepl('adult_', rep1) ~ stringr::str_split(rep1, 'adult_', simplify = TRUE)[, 2],
      TRUE ~ rep1),
    rep2 = case_when(
      grepl('adult_', rep2) ~ stringr::str_split(rep2, 'adult_', simplify = TRUE)[, 2],
      TRUE ~ rep2))
```

```{r}
hc <- hclust(as.dist(1 - corr_mat_p))

corr_long_p <- corr_long_p |>
  mutate(rep1 = factor(rep1, levels = hc$labels[hc$order]), 
         rep2 = factor(rep2, levels = hc$labels[hc$order]))
```

```{r}
corr_long_p |>
  ggplot(aes(rep1, rep2, fill= correlation)) + 
    ggtitle('Proteomics data') +
    geom_tile(aes(fill = correlation), colour = "black") +
    scale_fill_gradientn(colors = c('blue', 'white', 'red')) +
    theme(axis.text.x = element_text(angle = 45, hjust = 1), 
          axis.title = element_blank(),
          plot.title = element_text(face = "bold", hjust = 0.5)) 
```

Transriptomics data

```{r}
clean_3 <- clean_3 |> 
  select(c(1:21)) |>
  mutate(across(everything(), as.numeric)) |>
  rename_with(
    .fn = ~stringr::str_replace(.x, "rpkm_", ""), 
    .cols = starts_with("rpkm_")
  )
```

```{r}
corr_mat_t <- cor(clean_3, use = "pairwise.complete.obs", method = "pearson")

corr_long_t <- corr_mat_t |>
  as.data.frame() |>
  rownames_to_column("rep1") |>
  pivot_longer(
    cols = -rep1,
    names_to = "rep2",
    values_to = "correlation"
  )

corr_long_t <- corr_long_t |>
  mutate(
    rep1 = case_when(
      grepl('adult_', rep1) ~ stringr::str_split(rep1, 'adult_', simplify = TRUE)[, 2],
      TRUE ~ rep1),
    rep2 = case_when(
      grepl('adult_', rep2) ~ stringr::str_split(rep2, 'adult_', simplify = TRUE)[, 2],
      TRUE ~ rep2),
    rep1 = case_when(
      grepl('cortical_', rep1) ~ stringr::str_split(rep1, 'cortical_', simplify = TRUE)[, 2],
      TRUE ~ rep1),
    rep2 = case_when(
      grepl('cortical_', rep2) ~ stringr::str_split(rep2, 'cortical_', simplify = TRUE)[, 2],
      TRUE ~ rep2))
```

```{r}
hc <- hclust(as.dist(1 - corr_mat_t))
corr_long_t <- corr_long_t |>
  mutate(rep1 = factor(rep1, levels = hc$labels[hc$order]), 
         rep2 = factor(rep2, levels = hc$labels[hc$order]))
```

```{r}
corr_long_t |>
  ggplot(aes(rep1, rep2, fill= correlation)) + 
    ggtitle('Transcriptomics data') +
    geom_tile(aes(fill = correlation), colour = "black") +
    scale_fill_gradientn(colors = c('blue', 'white', 'red')) +
    theme(axis.text.x = element_text(angle = 45, hjust = 1), 
          axis.title = element_blank(),
          plot.title = element_text(face = "bold", hjust = 0.5)) 
```
